### ISSUE TITLE
Scrapy

### ISSUE THREAD

**Issue by skynorreply** [hvignolo87/tito#10]
Hola. Vi que después de mucho tiempo cambiaste el repositorio y agregaste Scrapy. Me gustaría entender por qué usar el rastreador web. ¿Es imprescindible utilizar Scrapy? mi consulado ya tiene las fechas y horarios definidos.

Gracias.

**Comment by hvignolo87** [comment]
Hola @skynorreply,

De momento sólo estoy haciendo pruebas para ver de qué forma se puede acelerar el proceso.

Saludos.
