### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by thexiox** [hvignolo87/tito#2]
Hola, quería saber si este bot ya ha funcionado o si aun lo estas intentando. Saludos

**Comment by hvignolo87** [comment]
> Hola, quería saber si este bot ya ha funcionado o si aun lo estas intentando. Saludos

Cómo estás?

Está probado y funcionando para el servicio _notarial_. Para el resto debería funcionar también, pero como los turnos son a partir de las 19hs AR, no tuve oportunidad de probarlo todavía.

En los próximos días lo haré y si no funciona algo lo arreglo.

Saludos!
