### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by smat-al** [hvignolo87/tito#5]
hello
its work like asharm, just one thing please , if no date found, can it try by it self, i mean when a set an hour for staring, its give me that there is no available date ( all are full ), how to make trying automaticly?
thanks.

**Comment by hvignolo87** [comment]
Hi @smat-al,

I'm not sure to understand your doubt. 

The script looks for an available day within a 18 months window. If doesn't find any, it ends.

I don't understand the behavior that hoy describe here:

> i mean when a set an hour for staring, its give me that there is no available date ( all are full ), how to make trying automaticly?

**Comment by smat-al** [comment]
sorry for my bad english, i meant, in stead of ends retry untill pick an appointment  (you said If doesn't find any, it ends).

**Comment by hvignolo87** [comment]
If there isn't any single day available within the next 18 months, what's the point on retrying in the exact same moment?
Here un Argentina there are a little few days available each day (if you are lucky), while there are thousands of people trying to get one. They take it in matter of seconds.

Maybe you're trying to use it for another similar thing?

**Comment by smat-al** [comment]
im trying to use it in the same website for another country, morocco, where there no available appointement you have to check every minute to get one, that why we dont know in witch our we can take the appointment, as for it's more than 1 mount that im trying to get one but in vain.

**Comment by hvignolo87** [comment]
Ok, now I understand. 

In that case, I think that you may consider forking the repository and modifying the while loop in main.py in order to get that behavior.

Other possibility is launching the script every minute manually.

**Comment by smat-al** [comment]
can please help me to do that if possible
thanks again

**Comment by hvignolo87** [comment]
Sorry but right now I haven't enough time for that.
